name: Run Training Script Daily

on:
  schedule:
    # Run daily at midnight
    - cron: '0 0 * * *'

jobs:
  training-script-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Fetch Latest Data from Hopsworks
      env:
        HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
      run: |
        python src/feature_store/fetch_hopsworks_data.py

    - name: Preprocess Data
      run: |
        python src/training/preprocess.py

    - name: Train the Model
      env:
        HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
      run: |
        python src/training/train_model.py
